# In _config.yml
title: Image data science with Python and Napari @LIBREhub @Napari 2023
author: Marcelo Leomil Zoccoler, Juan Nunez-Iglesias, Julián Mejía, Adan O. Guerrero Cardenas, Tobias Wenzel
logo: LatAmBio_Logo.png
execute:
  execute_notebooks: off

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

  # Information about where the book exists on the web
repository:
  url: https://github.com/LIBREhub/napari-LatAm-workshop-2023 # Online location of your book
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <p>
    Copyright: This work by Marcelo Leomil Zoccoler, Juan Nunez-Iglesias, Julián Mejía, Adan O. Guerrero Cardenas, Tobias Wenzel and Robert Haase can be reused under the terms of the <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC-BY 4.0</a> license unless mentioned otherwise.
    </p>
sphinx:
  config:
    html_show_copyright: false
